faculty/urls.py
from django.urls import path
from . import views

app_name = "faculty"

urlpatterns = [
    path("", views.teacher_dashboard, name="teacher_dashboard"),
    path("teacherlogin/", views.teacher_login, name="teacher_login"),
    path("teacherlogout/", views.teacher_logout, name="teacher_logout"),
    path("teacher-profile/", views.teacher_profile, name="teacher_profile"),
    path("createexam/", views.create_exam, name="create_exam"),
    path("manageexam/", views.manage_exam, name="manage_exam"),
    path("add-question/<int:exam_id>", views.add_question, name="add_question"),
    path("manageexam/<int:exam_id>", views.update_exam, name="update_exam"),
    path("manage-question/<int:question_id>", views.update_question, name="update_question"),
    path("exam/<int:exam_id>/add-question", views.add_question, name="add_question"),
    path("exam/<int:exam_id>/delete-question/<int:question_id>", views.delete_question, name="delete_question"),
    path("manage_material/", views.manage_material, name="manage_material"),
    path("material-delete/<int:material_id>", views.delete_material, name="delete_material"),
    path("manage-timetable/", views.manage_timetable_semester_list, name="manage_timetable"),
    path("manage-timetable/<int:semester>", views.manage_timetable_by_semester, name="manage_timetable_semester"),
    path("show-timetable/", views.show_timetable, name="show_timetable"),
    path("attendance-timetable/", views.attendance_timetable, name="attendance_timetable"),
    path("take-attendance/<int:lecture_id>/", views.take_attendance, name="take_attendance"),
    path('attendance/', views.attendance_semester_list, name='attendance_semester_list'),
    path('attendance/<int:semester>/', views.attendance_by_semester, name='show_attendance'),

]

lms_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("student.urls", namespace="student")),
    path("faculty/", include("faculty.urls", namespace="faculty")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from . import views

app_name = "student"

urlpatterns = [
    path("student/", views.student_dashboard, name="student_dashboard"),
    path("", views.student_login, name='login'),
    path('student/logout/', views.user_logout, name='logout'),
    path("student/profile/", views.student_profile, name="student_profile"),
    path("student/available-exams", views.available_exams, name="available_exams"),
    path("student/start-exam/<int:exam_id>", views.start_exam, name="start_exam"),
    path("student/student_material/", views.student_material, name="student_material"),
    path("student/time-table/", views.time_table, name="time_table"),
    path("student/show-attendance/", views.student_show_attendance, name="student_show_attendance"),
    path("student/attendance-percentage/", views.attendance_percentage, name="attendance_percentage"),
]

faculty/models.py
from django.db import models
from django.contrib.auth import get_user_model
from users.models import Department
from student.models import StudentProfile

# Create your models here.

CustomUser = get_user_model()

ROLE_CHOICES = (
    ('faculty', 'Faculty'),
    ('hod', 'HOD'),
    ('principal', 'Principal'),
)

def teacher_profile_upload_path(instance, filename):
    return f"teacher_profile/{instance.teacher_id}/{filename}"

class TeacherProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, blank=True, null=True)

    profile_picture = models.ImageField(upload_to=teacher_profile_upload_path, blank=True, null=True)

    full_name = models.CharField(max_length=150)
    date_of_birth = models.DateField(null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    information = models.TextField(null=True, blank=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    subject_specialization = models.CharField(max_length=100, null=True, blank=True)
    joining_date = models.DateField(null=True, blank=True)
    phone_number = models.CharField(max_length=15, null=True)
    email = models.EmailField(null=True, blank=True, default="default@clg.com")
    experience_year = models.IntegerField(default=0)

    teacher_role = models.CharField(max_length=20, choices=ROLE_CHOICES, null=True, blank=True)
    # all fields to create teacher profile
    teacher_id = models.CharField(max_length=20, unique=True, null=True, blank=True)
    password = models.CharField(max_length=128, default=3398)

    def save(self, *args, **kwargs):
        # if not user create user
        if not self.user:
            user = CustomUser.objects.create_user(
                username=self.teacher_id,
                teacher_id = self.teacher_id,
                password=self.password,
                user_type='teacher'
            )

            self.user = user
        super(TeacherProfile, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.full_name}"




def material_upload_path(instance, filename):
    return f"teacher_materials/{instance.teacher.teacher_id}/{filename}"


class TeacherMaterial(models.Model):
    teacher = models.ForeignKey(TeacherProfile, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    file = models.FileField(upload_to=material_upload_path)
    upload_at  = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        # automatically set department if not 
        if not self.department:
            self.department = self.teacher.department
        super(TeacherMaterial, self).save(*args, **kwargs)





#  for time table
DAYS_OF_WEEK = [
    ("Monday", "Monday"),
    ("Tuesday", "Tuesday"),
    ("Wednesday", "Wednesday"),
    ("Thursday", "Thursday"),
    ("Friday", "Friday"),
    ("Saturday", "Saturday"),
]

class TimeTable(models.Model):
    department =  models.ForeignKey(Department, on_delete=models.CASCADE)
    teacher = models.ForeignKey(TeacherProfile, on_delete=models.CASCADE)

    semester = models.IntegerField()
    subject_name = models.CharField(max_length=100)
    day = models.CharField(max_length=10, choices=DAYS_OF_WEEK)
    date = models.DateField(null=True, blank=True)
    start_time = models.TimeField()
    end_time = models.TimeField()

    def __str__(self):
        return self.subject_name




# #######################################################################
# #######################################################################


class Attendance(models.Model):
    student = models.ForeignKey(StudentProfile, on_delete=models.CASCADE)
    lecture = models.ForeignKey(TimeTable, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=15, choices=(('Present', 'Present'), ('Absent', 'Absent')))

    class Meta:
        unique_together = ('student', 'lecture', 'date')  # Optional but recommended

    def __str__(self):
        return self.student.full_name

faculty/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from users.models import CustomUser
from django.contrib.auth.decorators import login_required
from .models import TeacherProfile, TeacherMaterial, TimeTable, Attendance
from exam.models import Exam, Question, Option, Notification
from student.models import StudentProfile
from django.http import Http404
from django.contrib import messages
from django.utils.timezone import make_aware
from django.utils import timezone
from datetime import datetime, date


# Create your views here.


@login_required
def teacher_dashboard(request):
    teacher_info = None
    if request.user.is_authenticated:
        try:
            teacher_info = TeacherProfile.objects.get(user=request.user)
        except TeacherProfile.DoesNotExist:
            teacher_info = None
    
    notifications = Notification.objects.filter(target_user__in=['faculty', 'both']).order_by('-created_at')
    return render(request, "faculty/teacher_dashboard.html", {'teacher_info': teacher_info,
                                                              'notifications': notifications})

@login_required
def teacher_profile(request):
    teacher_info = None
    
    # get teacher 
    if request.user.is_authenticated:
        try:
            teacher_info = TeacherProfile.objects.get(user=request.user)
        except TeacherProfile.DoesNotExist:
            teacher_info = None
    
    return render(request, "faculty/teacher_profile.html", {'teacher_info': teacher_info})


def teacher_login(request):
    if request.method == "POST":
        teacher_id = request.POST.get('teacher_id')
        password = request.POST.get('password')


        try:
            #  Find by teacher id
            user = CustomUser.objects.get(teacher_id=teacher_id, user_type='teacher')
        
        except CustomUser.DoesNotExist:
            user = None

        if user is not None:
            # authenticate user
            user = authenticate(request, username=user.username, password=password)
            if user is not None:
                login(request, user)
                return redirect("faculty:teacher_dashboard")
            else:
                return render(request,"faculty/teacher_login.html")
        else:
            return render(request,"faculty/teacher_login.html")
    return  render(request,"faculty/teacher_login.html")


def teacher_logout(request):

    logout(request)
    return redirect("faculty:teacher_login")


@login_required
def create_exam(request):
    # get teacher profile
    teacher = TeacherProfile.objects.get(user=request.user)

    if request.method == "POST":
        title = request.POST.get('title')
        description = request.POST.get("description")
        samester = request.POST.get("semester")
        start_time = request.POST.get('start_time')
        end_time = request.POST.get('end_time')
        duration_minutes = request.POST.get('duration_minutes')


        # Now create Exam
        exam = Exam.objects.create(
            title=title,
            description=description,
            teacher=teacher,
            department=teacher.department,
            samester=samester,
            start_time=start_time,
            end_time=end_time,
            duration_miniutes=duration_minutes,

        )

        return redirect('faculty:add_question', exam_id=exam.id)



    return render(request, "faculty/teacher_exam_create.html")
    

@login_required
def add_question(request, exam_id):
    # get the exam with exam_id


    exam = get_object_or_404(Exam, id=exam_id)

    # check if current teacher created exam or not
    if request.user !=exam.teacher.user:
        raise Http404("You are not authorized to add questions")
    
    if request.method == "POST":
        question_text = request.POST.get("question_text")
        marks = request.POST.get('marks')

        question = Question.objects.create(
            exam=exam,
            text=question_text,
            marks=marks
        )

        # now for options

        option_texts = request.POST.getlist('option_texts')
        correct_option = request.POST.get('correct_option')


        for idx, option_text in enumerate(option_texts):
            is_correct = (str(idx) == correct_option)

            Option.objects.create(
                question=question,
                text=option_text,
                is_correct=is_correct
            )

            return redirect('faculty:add_question', exam_id=exam.id)
        
        

    
    return render(request, "faculty/teacher_add_question.html")


@login_required
def manage_exam(request):
    exams = Exam.objects.all()

    return render(request, 'faculty/teacher_manage_exam.html', {'exams': exams})


@login_required
def update_exam(request, exam_id):
    exam = get_object_or_404(Exam, id=exam_id)
    questions = Question.objects.filter(exam=exam).prefetch_related("Options")

    if request.method == "POST":
        try:
            #  ------------------- UPDATE EXAM INFO --------------------------------
            exam.title = request.POST.get('exam_title')
            exam.description = request.POST.get('description')
            exam.samester = request.POST.get('exam_samester')
            exam.duration_miniutes = request.POST.get('exam_duration')
            exam.start_time = request.POST.get('start_time')
            exam.end_time = request.POST.get('end_time')
            exam.save()
            messages.success(request, "Exam Info Update Succesfully")

        except Exception as e:
            messages.error(request, f"Error Occured {e}")

    context = {
        'exam': exam,
        'questions': questions
    }
    return render(request, "faculty/teacher_update_exam.html", context)


@login_required
def update_question(request, question_id):
    question = get_object_or_404(Question, id=question_id)

    if request.method == "POST":
        try:
            question.text = request.POST.get(f"q_text_{question.id}")
            question.marks = request.POST.get(f"q_marks_{question.id}")
            question.save()

            correct_option_id = request.POST.get(f"q_correct_{question.id}")
            for option in question.Options.all():
                option_text = request.POST.get(f"q_option_{question.id}_{option.id}")
                option.text = option_text
                option.is_correct = (str(option.id) == correct_option_id)
                option.save()
            
            messages.success(request, "Question and options updated successfully!")

        except Exception as e:
            messages.error(request, "Error Occured {e}")
    
    return redirect("faculty:update_exam", exam_id=question.exam_id)



@login_required
def add_question(request, exam_id):
    exam = get_object_or_404(Exam, id=exam_id)

    if request.method == "POST":
        q_text = request.POST.get("question_text")
        marks = request.POST.get("marks")
        options = request.POST.getlist("options")
        correct_index = request.POST.get("correct_option")

        if not options or len(options) < 2:
            messages.error(request, "Please provide at least two options.")
            return redirect("faculty:update_exam", exam_id=exam.id)

        if correct_index is None:
            messages.error(request, "Please select the correct option.")
            return redirect("faculty:update_exam", exam_id=exam.id)

        correct_index = int(correct_index)

        question = Question.objects.create(
            exam=exam,
            text=q_text,
            marks=marks
        )

        for idx, opt_text in enumerate(options):
            Option.objects.create(
                question=question,
                text=opt_text.strip(),
                is_correct=(idx == correct_index)
            )

        messages.success(request, "Question Added Successfully")
        return redirect("faculty:update_exam", exam_id=exam.id)

    return redirect("faculty:update_exam", exam_id=exam.id)

@login_required
def delete_question(request, exam_id, question_id):
    # Retrieve the exam and question
    exam = get_object_or_404(Exam, id=exam_id)
    question = get_object_or_404(Question, id=question_id, exam=exam)

    # # Debugging to print user and teacher info
    # print(f"Exam Teacher: {exam.teacher}")
    # print(f"Logged-in User: {request.user}")
    # print(f"Exam Teacher ID: {exam.teacher.id}")
    # print(f"Logged-in User ID: {request.user.id}")
    print(f"exam teacher user -- {exam.teacher.user}")
    print(f"request user -- {request.user}")

    # Check if the current user is the teacher of the exam
    if exam.teacher.user != request.user:  # Compare user IDs
        messages.error(request, "You don't have permission to delete this question")
        return redirect("faculty:update_exam", exam_id=exam.id)

    # Delete the question and all related options (because of on_delete=models.CASCADE)
    question.delete()

    messages.success(request, "Question deleted successfully")
    return redirect("faculty:update_exam", exam_id=exam.id)


@login_required
def manage_material(request):
    teacher_profile = get_object_or_404(TeacherProfile, user=request.user)
    materials = TeacherMaterial.objects.filter(department=teacher_profile.department)

    if request.method == "POST":
        title = request.POST.get("material_title")
        file = request.FILES.get("material_file")

        # now upload
        if title and file:
            TeacherMaterial.objects.create(
                teacher=teacher_profile,
                department=teacher_profile.department,
                title=title,
                file=file
            )

            messages.success(request, "Material Create Succesfully")
            return redirect("faculty:manage_material")

    return render(request, "faculty/teacher_manage_materials.html", {'materials': materials})

@login_required

templates/faculty/attendance_semester_list.html
{% extends 'faculty/teacher_base.html' %}
{% block content %}
<div class="container mt-4">
    <h3>Select Semester to View Attendance</h3>
    <div class="row">
        {% for sem in semesters %}
        <div class="col-md-4">
            <div class="card mb-3">
                <div class="card-body">
                    <h5>Semester {{ sem }}</h5>
                    <a href="{% url 'faculty:show_attendance' sem %}" class="btn btn-primary">View Attendance</a>
                </div>
            </div>
        </div>
        {% empty %}
        <p>No semesters found.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/faculty/teacher_manage_timetable_semester_list.html
{% extends 'faculty/teacher_base.html' %}
{% block content %}
<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-5 align-self-center">
                <h4 class="page-title">Available Semester</h4>
            </div>
            <div class="col-7 align-self-center">
                <div class="d-flex align-items-center justify-content-end">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="#">Home</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">Available Semester</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-2" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}

    <div class="container-fluid">
        <!-- row -->
        <div class="row">

            {% for sem in semester %}
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">Semester - {{ sem }}</h3>


                        <a href="{% url 'faculty:manage_timetable_semester' sem %}"
                            class="btn {% cycle 'btn-success' 'btn-primary' 'btn-danger' 'btn-info' %}">
                            Manage TimeTable
                        </a>
                        <!-- Bootstrap Modal -->


                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>

</div>
{% endblock %}

templates/faculty/teacher_update_exam.html
{% extends 'faculty/teacher_base.html' %}

{% block content %}
<div class="page-wrapper">
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-5 align-self-center">
                <h4 class="page-title">Update Exam</h4>
            </div>
            <div class="col-7 align-self-center">
                <div class="d-flex align-items-center justify-content-end">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="/faculty/">Home</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">Update Exam</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-2" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <form method="POST" action="{% url 'faculty:update_exam' exam.id %}">
                        {% csrf_token %}
                        <div class="form-body">
                            <div class="card-body" style="padding-top: 0;">
                                <div class="row p-t-20">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label">Exam Title</label>
                                            <input type="text" name="exam_title" class="form-control" value="{{ exam.title }}">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Description</label>
                                            <textarea name="description" class="form-control" rows="3">{{ exam.description }}</textarea>
                                        </div>
                                        <p>DEBUG: {{ exam.description }}</p>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Department</label>
                                            <input type="text" class="form-control" value="{{ exam.department.name }}" disabled>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Samester</label>
                                            <input type="text" name="exam_samester" class="form-control" value="{{ exam.samester }}">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Start Time</label>
                                            <input type="datetime-local" name="start_time" class="form-control" value="{{ exam.start_time|date:'Y-m-d\\TH:i' }}" required>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>End Time</label>
                                            <input type="datetime-local" name="end_time" class="form-control" value="{{ exam.end_time|date:'Y-m-d\\TH:i' }}" required>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Exam Duration (Minutes)</label>
                                            <input type="text" name="exam_duration" class="form-control" value="{{ exam.duration_miniutes }}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="card-body">
                                    <button type="submit" class="btn btn-success">Save</button>
                                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addQuestionModal">
                                        ➕ Add Question
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- Existing Questions Loop -->
        <div class="row">
            {% for question in questions %}
            <div class="col-sm-4">
                <div class="card card-body">
                    <h4 class="card-title">Question {{ forloop.counter }}</h4>
                    <form method="POST" action="{% url 'faculty:update_question' question.id %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>Question Description</label>
                            <textarea name="q_text_{{ question.id }}" class="form-control" rows="3">{{ question.text }}</textarea>
                        </div>
                        <div class="form-group">
                            <label>Question Marks</label>
                            <input type="number" name="q_marks_{{ question.id }}" class="form-control" value="{{ question.marks }}">
                        </div>
                        <div class="form-group">
                            <label>Options</label>
                            {% for option in question.Options.all %}
                            <div class="d-flex align-items-center mb-2">
                                <input type="radio" name="q_correct_{{ question.id }}" value="{{ option.id }}" {% if option.is_correct %}checked{% endif %} class="mr-3">
                                <input type="text" name="q_option_{{ question.id }}_{{ option.id }}" class="form-control" value="{{ option.text }}">
                            </div>
                            {% endfor %}
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-success">Save</button>
                        </div>
                    </form>
                    <!-- Separate form to delete the question -->
            <form method="POST" action="{% url 'faculty:delete_question' exam.id question.id %}">
                {% csrf_token %}
                <div class="form-actions">
                <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this question?')">
                    Delete Question
                </button>
                </div>
            </form>
                </div>
            </div>
            {% endfor %}
        </div>

        <!-- Modal for Adding Question -->
        <div class="modal fade" id="addQuestionModal" tabindex="-1" role="dialog" aria-labelledby="addQuestionModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <form method="POST" action="{% url 'faculty:add_question' exam.id %}">
                    {% csrf_token %}
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="addQuestionModalLabel">Add Question</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label>Question Text</label>
                                <textarea name="question_text" class="form-control" required></textarea>
                            </div>
                            <div class="form-group">
                                <label>Marks</label>
                                <input type="number" name="marks" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label>Options</label>
                                {% for i in "1234" %}
                                <div class="d-flex mb-2">
                                    <input type="radio" name="correct_option" value="{{ forloop.counter0 }}" class="mr-2">
                                    <input type="text" name="options" class="form-control" placeholder="Option {{ forloop.counter }}" required>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success">Save Question</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



{% endblock %}